# Generated by Django 4.1.3 on 2023-12-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ice_cream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_cream_name', models.CharField(max_length=255)),
                ('ice_cream_type', models.CharField(max_length=255)),
                ('ice_cream_price', models.CharField(max_length=15)),
            ],
        ),
    ]
